# Makefile.msc - MSVC build, invoked as:
#
#     nmake /f Makefile.msc
#
# Requires cl.exe (a "Developer Command Prompt for VS" shell) and
# win_bison.exe / win_flex.exe on PATH.
#
# All sources live under src\. Windows-only replacements live under
# src\win\.
#
# Object files are written next to their sources.

CC      = cl.exe
RC      = rc.exe
BISON   = win_bison.exe
FLEX    = win_flex.exe

SRC     = src
WIN     = src\win

CFLAGS  = /nologo /W3 /Zi /Od /D_CRT_SECURE_NO_WARNINGS /DYY_NO_UNISTD_H /I$(SRC) /I$(WIN)
RCFLAGS = /nologo
LDFLAGS = /nologo /Zi /Fe:ussr.exe
LIBS    = user32.lib

TARGET  = ussr.exe

OBJS = \
    $(SRC)\ussr.obj \
    $(SRC)\pp.obj \
    $(SRC)\main.obj \
    $(SRC)\uno.obj \
    $(SRC)\ussr_oop_builtins.obj \
    $(SRC)\ussr_bytecode.obj \
    $(SRC)\parser.tab.obj \
    $(SRC)\lexer.obj \
    $(SRC)\prng64_xrp32.obj \
	$(SRC)\autocomplete.obj \
	$(SRC)\completion_fs_win32.obj \
    $(WIN)\process_win32.obj \
    $(WIN)\worstline.obj \
    $(WIN)\getopt.obj \
    ussr.res

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) $(LIBS)

# --- resources --------------------------------------------------------

ussr.res: ussr.rc ussr.ico
	$(RC) $(RCFLAGS) /fo ussr.res ussr.rc

# --- generated parser/lexer ------------------------------------------
# Skipped when PREGENERATED=1 is passed on the nmake command line.

!IFNDEF PREGENERATED
$(SRC)\parser.tab.c $(SRC)\parser.tab.h: $(SRC)\parser.y
	$(BISON) -d -o $(SRC)\parser.tab.c $(SRC)\parser.y

$(SRC)\lexer.c: $(SRC)\lexer.l $(SRC)\parser.tab.h
	$(FLEX) -o $(SRC)\lexer.c $(SRC)\lexer.l
!ENDIF

# --- object files -----------------------------------------------------

$(SRC)\ussr.obj: $(SRC)\ussr.c $(SRC)\ussr.h $(SRC)\uthash.h $(SRC)\uno.h $(SRC)\ussr_oop_builtins.h $(SRC)\process.h
	$(CC) $(CFLAGS) /c /Fo:$(SRC)\ussr.obj $(SRC)\ussr.c

$(SRC)\pp.obj: $(SRC)\pp.c $(SRC)\pp.h
	$(CC) $(CFLAGS) /c /Fo:$(SRC)\pp.obj $(SRC)\pp.c

$(SRC)\main.obj: $(SRC)\main.c $(WIN)\worstline.h $(WIN)\getopt.h $(SRC)\ussr.h $(SRC)\ussr_version.h $(SRC)\pp.h $(SRC)\uno.h $(SRC)\ussr_bytecode.h $(SRC)\ussr_oop_builtins.h $(SRC)\autocomplete.h
	$(CC) $(CFLAGS) /c /Fo:$(SRC)\main.obj $(SRC)\main.c

$(SRC)\uno.obj: $(SRC)\uno.c $(SRC)\uno.h $(SRC)\ussr.h
	$(CC) $(CFLAGS) /c /Fo:$(SRC)\uno.obj $(SRC)\uno.c

$(SRC)\ussr_oop_builtins.obj: $(SRC)\ussr_oop_builtins.c $(SRC)\ussr_oop_builtins.h $(SRC)\uno.h $(SRC)\ussr.h
	$(CC) $(CFLAGS) /c /Fo:$(SRC)\ussr_oop_builtins.obj $(SRC)\ussr_oop_builtins.c

$(SRC)\ussr_bytecode.obj: $(SRC)\ussr_bytecode.c $(SRC)\ussr_bytecode.h $(SRC)\ussr.h
	$(CC) $(CFLAGS) /c /Fo:$(SRC)\ussr_bytecode.obj $(SRC)\ussr_bytecode.c

$(SRC)\parser.tab.obj: $(SRC)\parser.tab.c $(SRC)\parser.tab.h
	$(CC) $(CFLAGS) /c /Fo:$(SRC)\parser.tab.obj $(SRC)\parser.tab.c

$(SRC)\lexer.obj: $(SRC)\lexer.c $(SRC)\parser.tab.h
	$(CC) $(CFLAGS) /c /Fo:$(SRC)\lexer.obj $(SRC)\lexer.c

$(SRC)\prng64_xrp32.obj: $(SRC)\prng64_xrp32.c $(SRC)\prng64_xrp32.h
	$(CC) $(CFLAGS) /c /Fo:$(SRC)\prng64_xrp32.obj $(SRC)\prng64_xrp32.c

# --- autocomplete ----------------------------------------------------

$(SRC)\autocomplete.obj: $(SRC)\autocomplete.c $(SRC)\autocomplete.h $(SRC)\completion_fs.h
	$(CC) $(CFLAGS) /c /Fo:$(SRC)\autocomplete.obj $(SRC)\autocomplete.c

$(SRC)\completion_fs_win32.obj: $(SRC)\completion_fs_win32.c $(SRC)\completion_fs.h
	$(CC) $(CFLAGS) /c /Fo:$(SRC)\completion_fs_win32.obj $(SRC)\completion_fs_win32.c

$(WIN)\process_win32.obj: $(WIN)\process_win32.c $(SRC)\process.h
	$(CC) $(CFLAGS) /c /Fo:$(WIN)\process_win32.obj $(WIN)\process_win32.c

$(WIN)\worstline.obj: $(WIN)\worstline.c $(WIN)\worstline.h
	$(CC) $(CFLAGS) /c /Fo:$(WIN)\worstline.obj $(WIN)\worstline.c

$(WIN)\getopt.obj: $(WIN)\getopt.c $(WIN)\getopt.h
	$(CC) $(CFLAGS) /c /Fo:$(WIN)\getopt.obj $(WIN)\getopt.c

clean:
	-del /q $(SRC)\*.obj $(WIN)\*.obj $(TARGET) *.pdb *.res 2>NUL
	-del /q $(SRC)\parser.tab.c $(SRC)\parser.tab.h $(SRC)\lexer.c 2>NUL

.PHONY: all clean