bin_PROGRAMS = ussr

ussr_SOURCES = \
    parser.y \
    lexer.l \
    ussr.c \
    ussr_bytecode.c \
    bestline.c \
    main.c \
    pp.c \
    uno.c \
    ussr_oop_builtins.c \
    prng64_xrp32.c
AM_CPPFLAGS = -I$(srcdir)

EXTRA_DIST = \
    ussr.h \
    ussr_bytecode.h \
    uno.h \
    ussr_oop_builtins.h \
    pp.h \
    bestline.h \
    uthash.h \
	prng64_xrp32.h
